FORMAT: 1A
HOST:http://api.spiderlog.net

#Spider Log API
Provide services for the Spider Log app family, recording the world's spider sightings

#Group Spiders
Access to Spider resources

## My Spider [/spiders{?page,size}]
### Get all my spider sightings [GET]

+ Parameters
    + page (required, number, `1`)... `page` number
    + size (required,number,`10`)... page `size`
    
+ Request

    + Header
                
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api.version: 1.0
        
+ Response 200 (application/json)
    
    + Header
    
            Etag: "euyfewuyfvew76f7"
            cache-control: max-age=600
    + Body
    
            {
                "page" :
                {
                    "number" : 1,
                    "size" : 10,
                    "totalPages" : 20
                },
                "spiders":
                [
                    {
                        "sightedAt" : "2014-08-29T07:00",
                        "imageUrl" : "https://s3-eu-west-1.amazonaws.com/uid-sdfeeddd/234234234/234234234_234234324-z.jpg",
                        "description" : "Spider I saw on the train",
                        "tags" : [
                            "stripy"
                        ]
                    },
                    {
                        "sightedAt" : "2014-08-29T07:00",
                        "imageUrl" : "https://s3-eu-west-1.amazonaws.com/uid-sdfsdfsdf/234234234/234234234_234234324-z.jpg",
                        "description" : "Spider I saw on the train",
                        "tags" : ["stripy"]
                    },{
                        "sightedAt" : "2014-08-29T07:00",
                        "imageUrl" : "https://s3-eu-west-1.amazonaws.com/uid-sdfsdfsdf/234234234/234234234_234234324-z.jpg",
                        "description" : "Spider I saw on the train",
                        "tags" : ["stripy"]
                    }
                ]
            }